name: JavaScript/TypeScript Quality Checks

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - '.eslintrc*'
      - 'tsconfig*.json'
      - 'complete-quality-suite/editions/javascript/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.tsx'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - 'pnpm-lock.yaml'
      - '.eslintrc*'
      - 'tsconfig*.json'
      - 'complete-quality-suite/editions/javascript/**'

concurrency:
  group: js-quality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [18, 20]
      fail-fast: false

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            */package-lock.json

      - name: 📦 Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
            */node_modules
          key: ${{ runner.os }}-npm-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ matrix.node-version }}-
            ${{ runner.os }}-npm-

      - name: 🔧 Install Dependencies
        run: |
          npm ci --prefer-offline --no-audit
          # Install global tools if needed
          npm install -g typescript ts-node

      - name: 🔍 Cache ESLint
        uses: actions/cache@v4
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/.eslintrc*', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: 🎨 Code Formatting Check
        run: |
          echo "🎨 Checking code formatting with Prettier..."
          npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}" || {
            echo "❌ Formatting issues found. Run 'npm run format' to fix."
            exit 1
          }

      - name: 📏 ESLint Analysis
        run: |
          echo "📏 Running ESLint analysis..."
          npx eslint . --ext .js,.jsx,.ts,.tsx --cache --cache-location .eslintcache --format=compact || {
            echo "❌ ESLint issues found. Run 'npm run lint -- --fix' to auto-fix."
            exit 1
          }

      - name: 🔤 TypeScript Type Checking
        if: hashFiles('tsconfig.json') != ''
        run: |
          echo "🔤 Running TypeScript type checking..."
          npx tsc --noEmit || {
            echo "❌ TypeScript type errors found."
            exit 1
          }

      - name: 🧹 Dead Code Detection
        run: |
          echo "🧹 Detecting dead code with ts-prune..."
          npx ts-prune --ignore "src/**/*.test.ts|src/**/*.spec.ts" || {
            echo "⚠️  Dead code detected but not failing build"
          }

      - name: 🔒 Security Analysis
        run: |
          echo "🔒 Running security analysis..."
          npm audit --audit-level=high || {
            echo "❌ High-severity vulnerabilities found. Run 'npm audit fix' to resolve."
            exit 1
          }

      - name: 📊 Code Complexity Analysis
        run: |
          echo "📊 Analyzing code complexity..."
          if [ -f "complete-quality-suite/editions/javascript/quality-check.js" ]; then
            node complete-quality-suite/editions/javascript/quality-check.js eslint-complexity || {
              echo "⚠️  High complexity detected but not failing build"
            }
          fi

      - name: 📋 Code Duplication Check
        run: |
          echo "📋 Checking for code duplication..."
          if [ -f "complete-quality-suite/editions/javascript/duplication-check.js" ]; then
            node complete-quality-suite/editions/javascript/duplication-check.js || {
              echo "⚠️  Code duplication detected but not failing build"
            }
          fi

      - name: 📈 Maintainability Analysis
        run: |
          echo "📈 Analyzing maintainability..."
          if [ -f "complete-quality-suite/editions/javascript/maintainability-check.js" ]; then
            node complete-quality-suite/editions/javascript/maintainability-check.js || {
              echo "⚠️  Low maintainability detected but not failing build"
            }
          fi

      - name: 🧪 Unit Tests
        run: |
          echo "🧪 Running unit tests..."
          if npm run test --if-present; then
            echo "✅ All tests passed"
          else
            echo "❌ Some tests failed"
            exit 1
          fi

      - name: 📊 Upload Coverage Reports
        if: hashFiles('coverage/lcov.info') != ''
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false
          verbose: true

      - name: 📝 Generate Quality Report
        if: always()
        run: |
          echo "📝 Generating quality report..."
          mkdir -p reports
          echo "# Quality Report - Node.js ${{ matrix.node-version }}" > reports/quality-report.md
          echo "Generated on: $(date)" >> reports/quality-report.md
          echo "" >> reports/quality-report.md
          
          # Add results summary
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ **Status**: PASSED" >> reports/quality-report.md
          else
            echo "❌ **Status**: FAILED" >> reports/quality-report.md
          fi

      - name: 📤 Upload Quality Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quality-reports-node-${{ matrix.node-version }}
          path: |
            reports/
            coverage/
            .eslintcache
          retention-days: 7

  # Separate job for performance checks
  performance-analysis:
    name: Performance Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event_name == 'pull_request'

    steps:
      - name: 🔄 Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: npm ci --prefer-offline --no-audit

      - name: 🚀 Bundle Size Analysis
        run: |
          echo "🚀 Analyzing bundle size..."
          if npm run build --if-present; then
            # Check if build output exists
            if [ -d "dist" ] || [ -d "build" ] || [ -d ".next" ]; then
              echo "✅ Build successful - bundle analysis available"
              
              # Basic size check
              find dist build .next -name "*.js" -o -name "*.css" 2>/dev/null | while read file; do
                size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null || echo "0")
                echo "📁 $file: $(($size / 1024))KB"
              done
            fi
          else
            echo "⚠️  No build script found - skipping bundle analysis"
          fi

  # Summary job that depends on all checks
  quality-summary:
    name: Quality Summary
    runs-on: ubuntu-latest
    needs: [quality-checks, performance-analysis]
    if: always()

    steps:
      - name: 📊 Quality Check Summary
        run: |
          echo "📊 JavaScript/TypeScript Quality Check Summary"
          echo "=============================================="
          
          if [ "${{ needs.quality-checks.result }}" == "success" ]; then
            echo "✅ Quality checks: PASSED"
          else
            echo "❌ Quality checks: FAILED"
          fi
          
          if [ "${{ needs.performance-analysis.result }}" == "success" ] || [ "${{ needs.performance-analysis.result }}" == "skipped" ]; then
            echo "✅ Performance analysis: OK"
          else
            echo "❌ Performance analysis: FAILED"
          fi
          
          # Fail if quality checks failed (but allow performance to be optional)
          if [ "${{ needs.quality-checks.result }}" != "success" ]; then
            echo "❌ Overall result: FAILED"
            exit 1
          else
            echo "✅ Overall result: PASSED"
          fi 